name: infinity_ecom_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.1+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  chewie: ^1.13.0
  flutter_credit_card: ^4.1.0
  flutter_lints: ^5.0.0
  flutter_localization: ^0.3.3
  flutter_staggered_grid_view: ^0.7.0
  font_awesome_flutter: ^10.12.0
  info_getter: ^1.0.0
  store_box: ^2.0.0
  video_player: ^2.10.1
  video_thumbnail: ^0.5.6
  youtube_player_flutter: ^9.1.3
  firebase_core: ^4.3.0
  firebase_messaging: ^16.1.0
  flutter_downloader: ^1.12.0
  get: 4.7.3
  go_router: ^17.0.1
  provider: ^6.1.5+1
  shared_value: ^3.0.0
  one_context: ^4.1.0
  http: ^1.6.0
  intl: ^0.20.2
  flutter_local_notifications: ^19.5.0
  shared_preferences: ^2.5.4
  flutter_facebook_auth: ^7.1.5
  google_sign_in: ^6.1.0
  google_maps_flutter: ^2.14.0
  url_launcher: ^6.3.2
  image_picker: ^1.2.1
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  flutter_svg: ^2.2.3
  cached_network_image: ^3.4.1
  carousel_slider: ^5.1.1
  cupertino_icons: ^1.0.8
  webview_flutter: ^4.13.1
  intl_phone_number_input: ^0.7.5
  flutter_rating_bar: ^4.0.1
  flutter_localizations:
    sdk: flutter
  file_picker: ^10.3.8
  fluttertoast: ^9.0.0
  flutter_typeahead: ^5.2.0
  package_info_plus: ^9.0.0
  validators: ^3.0.0
  expandable: ^5.0.1
  flutter_countdown_timer: ^4.1.0
  flutter_html: ^3.0.0
  photo_view: ^0.15.0
  share_plus: ^12.0.1
  shimmer: ^3.0.0
  sign_in_with_apple: ^6.1.4
  webview_flutter_android: ^4.10.11
  crypto: ^3.0.7
  webview_flutter_wkwebview: ^3.23.5
  flip_card: ^0.7.0
  badges: ^3.1.2
  google_maps_place_picker_mb: ^3.1.2
  timeline_tile: ^2.0.0
  phonepe_payment_sdk: ^3.0.2
  route_transitions: ^2.0.1
  path: ^1.9.1
  flutter_spinkit: ^5.2.2
  flutter_chat_bubble: ^2.0.2

dependency_overrides:
  package_info_plus: ^9.0.0
  google_api_headers: ^5.1.0
  phonepe_payment_sdk: ^3.0.2
  badges: ^3.1.2
  crypto: ^3.0.7
  clipboard: ^3.0.14
  connectivity_plus: ^7.0.0
  dotted_line: ^3.2.3
  dropdown_search: ^6.0.2
  expandable: ^5.0.1
  flip_card: ^0.7.0
  file_picker: ^10.3.8
  flutter_spinkit: ^5.2.2
  flutter_math_fork: ^0.7.4
  flutter_typeahead: ^5.2.0
  flutter_rating_bar: ^4.0.1
  flutter_chat_bubble: ^2.0.2
  flutter_html: ^3.0.0
  flutter_countdown_timer: ^4.1.0
  flutter_staggered_grid_view: ^0.7.0
  google_fonts: ^7.0.1
  google_maps_place_picker_mb: ^3.1.2
  intl_phone_number_input: ^0.7.5
  json_annotation: ^4.9.0
  logging: ^1.3.0
  photo_view: ^0.15.0
  rename: ^3.1.0
  route_transitions: ^2.0.1
  shimmer: ^3.0.0
  share_plus: ^12.0.1
  sign_in_with_apple: ^6.1.1
  fluttertoast: ^9.0.0
  timeline_list: ^0.1.1
  timeline_tile: ^2.0.0
  validators: ^3.0.0
  webview_flutter_android: 4.10.11
  webview_flutter_wkwebview: ^3.23.5

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.4
  json_serializable: ^6.11.3
  flutter_launcher_icons: ^0.14.4
  change_app_package_name: ^1.5.0


flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_logo.png"
  remove_alpha_ios: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/htmls/
    - assets/fonts/

  fonts:
    - family: PublicSansSerif
      fonts:
        - asset: assets/fonts/PublicSans-Regular.ttf
        - asset: assets/fonts/PublicSans-Bold.ttf
        - asset: assets/fonts/PublicSans-Medium.ttf
        - asset: assets/fonts/PublicSans-SemiBold.ttf
        - asset: assets/fonts/PublicSans-Italic.ttf
          style: italic
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans-Regular.ttf
        - asset: assets/fonts/NotoSans-Medium.ttf
        - asset: assets/fonts/NotoSans-Bold.ttf
        - asset: assets/fonts/NotoSans-Italic.ttf
          style: italic